name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Send email notification
    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: niwanthiedirisinghe.95@gmail.com
        password: Ru4190416niwa#0
        subject: 'Java CI Build Success Notification'
        body: 'Your Java CI build completed successfully.'
        to: 'niwanthiedirisinghe.95@gmail.com'
        from: 'niwanthiedirisinghe.95@gmail.com'
